### ISSUE TITLE
./wave

### ISSUE THREAD

**Issue by caffeineaddiction** [MechMK1/mechmk1.me#2]
so long and thanks for all the fish

**Comment by MechMK1** [comment]
You're most welcome

**Comment by MechMK1** [comment]
@caffeineaddiction Since someone asked:

No, there was never a "discussion" between me and a CM, as in bi-lateral communication. I was banned and the only comment I received was as follows:

> Immediately mocking the very reason you were suspended for might not be the best idea.
>
> Your chat profile has been temporarily suspended for 365 days.
>
> Regards,
> Stack Exchange Community Management Team

It was never explained how I was "mocking" anyone. So please don't let any false rumors go around that there was some "discussion" or "argument". I was kicked out - plain and simple.

**Comment by caffeineaddiction** [comment]
Yah, I kinda figured as much but one of the mods said it was against the rules to discuss actions taken against users accounts.  I figured it would be best to not try my luck ;)
